// Dil Veri Tabanı (Bölüm 1 ve Bölüm 2 yüklü)
const translations = {
    en: {
        powered: "Powered By Cold Works Production",
        ch1_nav: "Chapter 1",
        ch2_nav: "Chapter 2",
        ch1_title: "The Chapter 1: Welcome to Home, Luna.",
        ch2_title: "The Chapter 2: Blue and Red",
        published_by: "Published & Distributed by",
        story1: [
            "Once upon a time there was someone called: \"Luna Starliy Starlife\", They live in a small contury called: The Dragwolfinh, they live with their sister Lina. They are time traveler and scientist, they are successful child to make their new plans. One day they made a potion but the potion makes people turn into monsters. Luna made something that can't change. Until blackwhite got created away. Blackwhite is a shapeshifter that can change into people. They are powerful and strong that can change the timeline of people. They wanna to control the world, One day blackwhite gets in the timeline and control Luna's memories. Luna gets deja vu's alot everyday, Luna see alots of sissours and gets scared of them. Luna realized something that Luna has sissour hand, a big sissour hand that makes Luna even more scared. Luna start to turn into a monster, Blackwhite. Luna trys to talk to their older child blackwhite, they tell them if they can fix them, luna will take care of them. Blackwhite turns luna into normal and let luna fix them. At home luna trys to fix it and it didn't work. Many days, weeks, months and they still try to help them but the potion that they made was not fixable enough. Luna wants to fix blackwhite but it was impossible. Blackwhite runs away and they wish to meet them sooner or later. Blackwhite for years they visit the old history of the world. Blackwhite wants to rule the world and the history of world. Luna on the other hand is working on a time machine that can fix people mostly blackwhite. Luna works everyday for this time machine so blackwhite can be fixed. They dreamed about fixing Blackwhite, they read books about fixing something that can make the world shift. If they can't fix Blackwhite, Blackwhite will destroy the world. Luna finally stoped bc they can't fix them so they trap them in a safety jar and make machine to put them in the jar. And it worked and Blackwhite was sad about this. 5 years later...",
            "<strong>Luna:</strong> i'm 17 years old now...i still working on new plans and hanging out with friends...but then i saw the safety jar opend and blackwhite ran away, maybe even far away...but i knew something was gonna happend. Then i'm here in the white void, silver's house...",
            "Silver kisses luna's hand and welcomed them like sweet home. Luna blushes harder and trys to act cool with it. Luna see silver's room full of luna's pictures.",
            "<strong>Silver:</strong> don't be scared when you saw that..i been wanted to meet you from along time darling...",
            "Silver gets close to their face, they both looks at each others but their eyes starts getting lustful. They kiss with closed eyes and locked mouths, they had their first welcome kiss. They look at each others slowly. Luna was shocked after what happend. They try to cover it put. Luna had wired taste on their mouth like mercury taste. Silver hold their hand.",
            "<strong>Silver:</strong> my name is silver mercury...",
            "<strong>Luna:</strong> my name is luna starliy starlife...it's nice to meet you silver...so how did you get here?",
            "<strong>Silver:</strong> well...i don't know, i was born here but i don't know where my family is. I don't know if i'm the only one but...yup this is life i guess?...",
            "Luna looks at them softly and luna give silver a blue bracele.",
            "<strong>Silver:</strong> wow...thank you luna...",
            "Luna and silver trys to escape the white void.",
            "<strong>Silver:</strong> so luna can we teleport to dragwolfinh?...luna???",
            "Luna started feeling strange, they look at their hands but silver see them look scared so he try to calm luna down.",
            "<strong>Silver:</strong> Hey...it's okay lun-lun..i'm here for you...",
            "<strong>Luna:</strong> okay...i'm ready...",
            "Luna's friends see luna and silver",
            "<strong>Filler:</strong> Luna! Finally your here...and who are you?",
            "<strong>Luna:</strong> well...everyone! This is silver mercury, he is my boyfriend..",
            "everyone was happy and excited about silver mercury. At the night time luna started making the beds for tonight. Silver was wearing some of luna's outfits.",
            "<strong>Lina:</strong> do you like any type of food silver?",
            "<strong>Silver:</strong> well i like pop tarts you know those snack thingy..",
            "<strong>Lina:</strong> wow that's great.",
            "Sliver happy to finally know people more of dragwolfinh. Luna and other fall asleep. Luna started having weird dreams that see blackwhite make luna go to a universe that luna has golden wings.",
            "<strong>Blackwhite:</strong> come on mom time to wake up...rise and shine luna...",
            "Luna got wake up by silver",
            "<strong>Silver:</strong> Luna! LUNA! thank god you woke up..",
            "<strong>Luna:</strong> ow..my back huh? I feel something behind my back..",
            "luna feels something behind their back and it was golden wings, luna started worried about that dream. It feels like a nightmare.",
            "<strong>Silver:</strong> are you okay luna?",
            "<strong>Luna:</strong> i'm fine...don't worry..",
            "Luna didn't wanna to explain it bc it will make it more strange.",
            "Tom calls luna",
            "<strong>Tom:</strong> hi luna do you wanna go outside today with others?",
            "<strong>Luna:</strong> yeah sure buddy hehe..",
            "At outside they started having fun, tom was flying with his wings. Luna was happy to see others happy. Dee Lee was happy and blushing for Tom bc dee lee has a crush on him from along time. Filler and mr.? And others was talking but then some broken evil robot called elly try to kill tom. And it did hurt tom's chest and tom fall down. People thought this was one of luna's old project so they started fighting.",
            "<strong>Rammy:</strong> LUNA IT WAS YOUR FAULT. THIS WAS ONE OF YOUR PROJECT IS IT?",
            "<strong>Luna:</strong> no..i swear it was not me...",
            "Tom was in the hospital for weeks and luna gives their wings so tom can fly again. Silver was jealous bc luna and tom was dating but they stopped bc they got more sexualized jokes from people at their old school. Dee lee was hoping tom to be okay.",
            "<strong>Silver:</strong> Luna...",
            "<strong>Luna:</strong> h-hey it's okay, i'm fine..",
            "<strong>Silver:</strong> it was not your fault..",
            "Luna was really upset about tom. Police lilith and kaylee comes to luna arrested them for the evil robot. At the police station they put luna on electric chair",
            "<strong>Police lilith:</strong> so doctor luna why did you do this to your friend tom?",
            "<strong>Luna:</strong> look i know elly was one of my old project but it was not me i swear!",
            "<strong>Police kaylee:</strong> liar! You did this to hurt more people don't you?",
            "<strong>Luna:</strong> no but why would i hurt anyone?",
            "<strong>Police kaylee:</strong> i don't know ask this to yourself first!",
            "They click on the electric botton. Luna was in pain.",
            "<strong>Luna:</strong> AHHHHHHGGGGG!! RAHHHHHHH!!",
            "They stoped it.",
            "<strong>Luna:</strong> ughh...i'm tired of this already...",
            "Silver was looking at luna. Police lilith and kaylee left luna alone, silver comes out with like a liquid.",
            "<strong>Silver:</strong> hi luna do you want help?",
            "<strong>Luna:</strong> sure...",
            "Silver pulls luna closer and kisses them with mercury liquid. luna feels more weird with the taste of the mercury. Luna and silver looked at each others and they kissed with love of each others. Luna and silver had this love feeling that they been feeling from along time. Silver helps luna to get out of the electric chair. Luna happy to finally have someone like silver. Luna and silver go to luna's secret lab.",
            "<strong>Luna:</strong> i crated elly just to make more plants, trees and other stuff..but maybe...",
            "luna realized blackwhite did this so they started their plan of Destroying luna. Luna wanted some time bc it was started to become more stranger.",
            "<strong>Filler:</strong> you know we could use the door not the window but anyways..luna what happend?",
            "Luna tell them what happend. Luna was looking for elly but rammy and lily was using it for fight robot. They been wanna to fight alot with people. Rammy is really good at fighting. Luna let them fight with the robot, at home luna was dressing up their home outfits and silver opens the door and see luna's arms and legs.",
            "<strong>Luna:</strong> don't look at me please..",
            "<strong>Silver:</strong> no your still look beautiful darling...",
            "Silver trys to touch it and it was kinda deep cuts, silver hold their arm and kiss it softly, luna was happy.",
            "<strong>Silver:</strong> luna do you wanna do something to make you feel okay?",
            "<strong>Luna:</strong> yeah okay!... ",
            "they started making out. Luna sits on silver's lap and they started kissing. Lina hear the sounds and opens the door and see them kissing. Lina close the door after seeing them. Luna and silver was looking at each others. Silver slowly hold their thigh, Luna look at silver blushing. They slowly touch their lips together. Luna and silver are like lovers after there is not much people in dragwolfinh. The love grows more and more when the time pass. They lay on the bed and sleep together. They hug each others while sleeping.",
            "<strong>Lina:</strong> well they were having fun time butttt...we have much fun time making food millie.",
            "<strong>Millie:</strong> hell yeah! Hehehe...",
            "They were making food together. They try to learn new types of food, so they started making new food. They eat the food together and it was really good. Meanwhile Silver wakes up and see Luna's collar and their golden heart necklace. He got up and opens the inside the heart, it has a power system that can make luna have golden powers. Silver slowly looks at the pictures in the walls, it was family and friends pictures, silver see a picture of luna and their family. Silver slowly started crying, he never had a family and he know their is nobody mercury person like him. Luna wakes up and see silver crying. They gets up and hugs silver before saying anything.",
            "<strong>Luna:</strong> don't worry i have a ink friend that you can meet with silver...",
            "the next day they go to Filler and Mr.?, they knew they will always be sweet to people. Mr.? Meets Silver and they did a dna test to see if they were a family members, they look at the results and they were cousins but they never see each others before. Silver was happy to see some memeber in their family. Luna was happy for silver. After that they go to Luna's dog bluey's grave, they look at the grave and silver noticed that luna started crying but without any sounds. Luna sits on the grass and silver looks at luna with sadness. He knows that losing someone you love is the worst thing in life. Luna slowly lay on the grass, silver sits in grass too, silver ask them what can make them remember their dog.",
            "<strong>Luna:</strong> that collar was my dog's collar..i wear it because i miss him...",
            "Silver realized after looking at the collar, he comes and hugs luna. Luna gets up after hugging silver and grabs shovel and started digging the grave. Silver was shocked.",
            "<strong>Silver:</strong> what are you doing?...",
            "<strong>Luna:</strong> what am i doing!? I'm digging. I can reborn him to life again!...",
            "They go to Luna's secret lab and they try to reborn bluey by machine that can make him alive again. Luna trys so many times but falied but they try one more time and it worked. Luna made bluey drink an potion that can make him not turn into a zombie. Luna also made a collar that can make bluey talk like us do. Bluey was reborn and luna was happy to finally see their dog again. They take bluey home. Lina was happy to see bluey again, luna was trying to get the bluey's dog stuff to the home again. Silver notice there isn't much dog food and silver looks around and see some dog bowl of rotten food.",
            "<strong>Silver:</strong> hey lina? Why there is rotten food on here?",
            "<strong>Lina:</strong> well...luna was eating rotten food when bluey died by car crash.",
            "Luna was looking at them with void eyes, no words yet.",
            "<strong>Luna:</strong> silver...can you take the rotten food to the trash..?",
            "Luna looks at bluey",
            "<strong>Luna:</strong> without bluey i would nothing for anyone...",
            "Bluey hugs Luna thightly.",
            "<strong>Bluey:</strong> it's all gonna be okay luna..."
        ],
        story2: [
            "Luna wakes up slowly. Looks at their back, silver was hugging them. They were with underwears, luna gets up and gets dressed up. Silver wakes up knowing they slept together. Silver smirks and looks at luna.",
            "<strong>Luna:</strong> don't even think about it silver.",
            "<strong>Silver:</strong> why don’t you like being here?",
            "<strong>Luna:</strong> I’m going to the dragwolfinh gods, they invited me so i can talk to them.",
            "<strong>Silver:</strong> so your going now..i thought we can have more time.",
            "<strong>Luna:</strong> stop. Stop. STOP. JUST FUCKING STOP!!!!",
            "Luna closed the door, silver confused but didn’t stop. Luna goes to the dragwolfinh gods as soon as possible.",
            "<strong>Luna:</strong> hello? Someone? Anyone???",
            "<strong>Miss gold:</strong> welcome dr. Luna starliy starlife… we invited you because we need you to help the world of melody of music.",
            "<strong>Mr.Star:</strong> we are giving you the music of life is the key.",
            "<strong>Mr.Devil:</strong> we are giving this because we need you to be stronger for people who hurts you. You are the one to make people’s peace so start now.",
            "<strong>Luna:</strong> so is this gonna make the world peace???",
            "<strong>Miss gold:</strong> yes sweetheart, this means you get to choose your path of life. Step by step each move makes you want to living fun…",
            "<strong>Luna:</strong> but what if i failed to do this things again and again will i still be with my friends?",
            "<strong>Miss gold:</strong> yes every move you make is a choice in your life even if it don’t feel right..",
            "<strong>Mr.star:</strong> but remember I’m always here if you wanna reset the timeline or delete it, still no matter how you try just keep try even if you’re sad and blue..I’m your childhood imagery friend okay? I need you to look up the sky of night time and see the stars and one of the big star is me…",
            "<strong>Luna:</strong> okay then…let’s start now..",
            "The dragwolfinh gods give luna an soul element, this element keeps them play the rhythm in their mind and heart. Luna started playing the rhythm of her heart…she gets an electrical guitar like her brother mike, luna feels relaxed and happy to play an melody in her mind…luna slowly opens her eyes as seeing the soul element.",
            "<strong>Luna:</strong> wow…i never felt this much okay..",
            "<em>flashbacks</em>",
            "Many years ago..Me (Luna) and Mike was close siblings…before mike raped and abused her…",
            "<strong>Mike:</strong> luna. Luna…….LUNAAAAAA!!!!!",
            "Luna snaps for an moment..she trying to lock the door. Mike tried to open it…",
            "<strong>Luna:</strong> NO YOU HURT ME!!! NO MIKE I DON’T WANT YOU…",
            "Luna takes an shower and there was blood driping in her legs. Luna starts crying in bathroom, luna waits until the blood stopped bleeding…Mike’s soul looks at luna’s body, mike looks at luna.",
            "<strong>Mike:</strong> are you trying to forget me luns?",
            "<strong>Luna:</strong> you get me under into my surfice of my scars. Now just leave me be here.",
            "<strong>Mike:</strong> you know you can’t win cuz you’re an loser, you never had an chance of winning. You look under of my bones see if i care enough for you.",
            "(It starts as an lovely smell of happines but look back at it makes they burn themselfs and used to be alright for it but times go by they started acting like an haters to each others. Simple mistakes make their dayly Health worst…)",
            "<strong>Mike:</strong> So are you gonna be quite or forgive me right now?",
            "<strong>Luna:</strong> No i will never for give you mike.",
            "<strong>Mike:</strong> what did you said!?!",
            "<strong>Luna:</strong> i said i don’t forgive you…",
            "Mike puts his hands on luna’s neck and burns her into like fire element.",
            "<strong>Luna:</strong> AHHHHHHHHH!!!…",
            "<strong>Mike:</strong> LUNA I GIVED YOU MANY CHANCES!!! DON’T YOU UNDERSTAND CORRECTLY?!!??! I needed you.",
            "<strong>Luna:</strong> MIKE LET ME GO!! I wanted you to go away first.",
            "Mike slaps at her and looks at her.",
            "<strong>Luna:</strong> i said stop.",
            "The silent fill the room with no regrets only pain. Luna slowly starts to fate away…mike in other hand just left the room to get some drinks. Luna swallows her pills and trys to get her last breaths. Luna gets dressed and walks outside at the night.",
            "<strong>Lina:</strong> Luna? What are you doing here?",
            "Lina sees the marks on her body…",
            "<strong>Lina:</strong> oh my god, who did this to you sister??",
            "<strong>Luna:</strong> umm..mike..",
            "<strong>Lina:</strong> wait mike!?! How??!",
            "Luna explains it to lina, lina wants to get revenge on mike.",
            "<strong>Luna:</strong> look i just need to get some feash air okay?",
            "<strong>Lina:</strong> but look at you you look like beaten up…",
            "<strong>Luna:</strong> I’ll be fine just go home okay?",
            "Luna drinks some wine to make it gone. Berri sees luna.",
            "<strong>Berri:</strong> luna what are you doing out here!?",
            "<strong>Luna:</strong> uh-uh-hey Berri~…",
            "<strong>Berri:</strong> sigh..okay luna I’m taking you to my house.",
            "At berri’s home…",
            "<strong>Luna:</strong> Ah-uh-umm..Berri? What are you doing?",
            "<strong>Berri:</strong> I’m trying to help the marks to go away, so how do you feel luns?",
            "<strong>Luna:</strong> oh i feel great now, I’m so sleepy right now.",
            "<strong>Berri:</strong> do you want me to sleep together?",
            "Luna and berri blushes, luna said yes so they sleep together.",
            "<strong>Berri:</strong> hey luna?",
            "<strong>Luna:</strong> yeah??",
            "<strong>Berri:</strong> i love you.",
            "<strong>Luna:</strong> i love you too berri…",
            "They kissed and fall asleep. At the morning berri got up and made breakfast to luna and himself.",
            "Luna sees an nightmare, she was the color blue with an blue world that looks like another place. Luna sees an red guy with horns, tail and devil wings.",
            "<strong>Luna:</strong> hello sir where am i right now?",
            "<strong>Red guy:</strong> this is the sadness world and also my name is mike.",
            "<strong>Luna:</strong> mike..? Okay mike but how can i escape in here??",
            "<strong>Mike:</strong> i don’t know but i can give you something you need…",
            "Mike give an small object.",
            "<strong>Luna:</strong> oh um this kinda hurts my fingers but thanks i guess…",
            "<strong>Mike:</strong> wait you are luna starliy starlife right?",
            "Luna looks shocked at first, mike looks at her with lust in his eyes.",
            "<strong>Mike:</strong> i guess that means yes, well then good luck Luna.",
            "Luna still wonder why this person gived her an small object. Luna looks at it, it was an sharp…Slowly the world starts raining with flood and luna drowns with it. Luna wakes up checks if there is scars, luna gets up looks at mirror. Luna’s hands was warm, berri notices her and checks on her.",
            "<strong>Berri:</strong> luna are you alright?",
            "Luna was out of breath.",
            "<strong>Berri:</strong> okay now slowly breath in and breath out. This will make you feel better.",
            "Luna starts breathing.",
            "<strong>Berri:</strong> so what happend?",
            "<strong>Luna:</strong> i saw an nightmare, an red guy named mike knows who i was…",
            "<strong>Berri:</strong> luna do you need an hug or anything?",
            "<strong>Luna:</strong> maybe an drink can make me okay.",
            "Luna drinks an beer, looks at berri.",
            "<strong>Luna:</strong> do you think mike is gonna come to me in future?",
            "<strong>Berri:</strong> i don’t know but I’ll protect you.",
            "<em>flashback ended</em>",
            "Berri look at luna’s house, berri now has an one eye scar on his eye. Berri sees silver.",
            "<strong>Berri:</strong> I wonder why this guy is with Luna.",
            "<strong>Xen:</strong> so you’re just gonna chase that guy to death?",
            "<strong>Berri:</strong> no no I’m just wondering…",
            "<strong>Xen:</strong> i see, you missed luna right?",
            "<strong>Berri:</strong> yeah but i don’t wanna make her worst again.",
            "Xen and Berri goes to luna’s house and knocks the door, silver opens it.",
            "<strong>Silver:</strong> oh hey are you looking for luna? Well she is not here so-",
            "<strong>Berri:</strong> no. We are gonna talk to you, silver mercury.",
            "Silver invite them in.",
            "<strong>Berri:</strong> so you’re luna’s new boyfriend right?",
            "<strong>Silver:</strong> yeah duh, what do you think i am?",
            "Berri gets mad, looks at silver.",
            "<strong>Berri:</strong> what is you’re purpose in here?",
            "<strong>Silver:</strong> well I’m gonna help her to get better.",
            "<strong>Berri:</strong> liar…",
            "Silver was confused.",
            "Berri starts punching silver, Xen looks but don’t helps him.",
            "<strong>Berri:</strong> I WAS HER FIRST BOYFRIEND, IF YOU JUST GONNA ACT NOTHING HAPPEND I’LL BEAT YOU TO DEATH.",
            "<strong>Silver:</strong> heh..so you’re her “bad boy” huh? Well guess what i was gonna rape her and-",
            "Berri gets the knife and stabs him, silver is an mercury so he has cyan blood.",
            "<strong>Silver:</strong> ugh! You’re sick for her berri. You’ll never understand how powerful i am.",
            "<strong>Berri:</strong> SHE WAS RAPED AND ABUSED BY HER TWIN BROTHER AND GIVED BIRTH TO AN BABY!!",
            "Silver was shocked.",
            "<strong>Silver:</strong> wait-",
            "<strong>Berri:</strong> NO I BET YOU ARE GONNA BE LIKE MIKE RIGHT!?!",
            "Maoki look at them…",
            "<strong>Maoki:</strong> dad…?",
            "<strong>Berri:</strong> maoki..",
            "<strong>Maoki:</strong> dad what are you doing?",
            "<strong>Berri:</strong> no go to you’re room we are talking seriously…",
            "<strong>Maoki:</strong> but dad-",
            "<strong>Berri:</strong> I SAID GO TO YOU’RE ROOM!!",
            "Maoki go to her room…",
            "<strong>Silver:</strong> so maoki is luna’s child..?",
            "<strong>Berri:</strong> yeah i never thought this guy hunts her to this day.",
            "<strong>Silver:</strong> look dude, i know this is serious but we can make her feel happy.",
            "<strong>Berri:</strong> guy like you makes me sick, silver!",
            "<strong>Silver:</strong> well at least you can help me to grow myself to make her feel okay.",
            "<strong>Berri:</strong> fine but if you hurt her feelings I’ll rip you into peices…",
            "Berri and Xen leaves the house, luna goes to berri.",
            "<strong>Luna:</strong> berri look I finally have powers and-",
            "<strong>Berri:</strong> listen we need to talk, luna.",
            "Luna was shocked and scared for an moment.",
            "<strong>Berri:</strong> luna, silver was gonna rape you.",
            "Luna was quite and slowly shakes.",
            "<strong>Luna:</strong> w-what?..berri i-",
            "<strong>Berri:</strong> i said your new boyfriend is gonna rape you.",
            "<strong>Luna:</strong> he..was gonna do that?",
            "<strong>Berri:</strong> yes i find out today with xen.",
            "Luna starts crying, berri looks at luna softly and hold their chin.",
            "<strong>Berri:</strong> baby, i know it’s hard but i-",
            "<strong>Luna:</strong> HOW CAN HE!? HE WAS MY EVERYTHING!!",
            "<strong>Berri:</strong> LUNA YOU WERE MY EVERYTHING WHEN WE FIRST DATING TOGETHER!!",
            "Luna looks at berri, berri’s tears starts to go down.",
            "<strong>Luna:</strong> do you want me to kiss you?",
            "<strong>Berri:</strong> i mean it’s your choice, I’m not an kissable man tho.",
            "Luna slowly kisses berri’s scrached eye and then his mouth…",
            "<strong>Luna:</strong> mh~ berri, you still taste the same as always.",
            "<strong>Berri:</strong> i missed you, luns.",
            "<strong>Luna:</strong> now i need to sing you as song.",
            "Luna sings an song for berri, later luna goes home and talks to silver",
            "<strong>Silver:</strong> luna welcome home.",
            "<strong>Luna:</strong> …",
            "<strong>Silver:</strong> honey why are you so quite?",
            "<strong>Luna:</strong> silver leave me alone.",
            "<strong>Silver:</strong> what-",
            "<strong>Luna:</strong> LEAVE ME ALONE!!!",
            "<strong>Silver:</strong> Luna I don’t understanding you.",
            "<strong>Luna:</strong> RAGHH! JUST FUCK OFF!!!",
            "Luna goes to maoki, looks at maoki",
            "<strong>Luna:</strong> baby, maoki",
            "<strong>Maoki:</strong> mommy, I’m scared…",
            "<strong>Luna:</strong> I’m here my child.",
            "Luna and Maoki hugs together. Maoki crys, in luna’s arms.",
            "<strong>Luna:</strong> baby, don't cry",
            "<strong>Maoki:</strong> am i an mistake mommy?",
            "<strong>Luna:</strong> no baby, your not. How told you that?",
            "<strong>Maoki:</strong> i saw someone name Mike in my dreams and he told me that.",
            "Luna was shocked, gived maoki them an plushie.",
            "<strong>Maoki:</strong> mommy?",
            "Luna was having an heart attack, and fell down.",
            "<strong>Maoki:</strong> MOMMY!!!",
            "Ambulans comes to the house and takes luna…"
        ]
    },
    tr: {
        powered: "Cold Works Production Tarafından Desteklenmektedir",
        ch1_nav: "Bölüm 1",
        ch2_nav: "Bölüm 2",
        ch1_title: "Bölüm 1: Eve Hoş Geldin, Luna.",
        ch2_title: "Bölüm 2: Mavi ve Kırmızı",
        published_by: "Yayıncı ve Dağıtıcı:",
        story1: [
            "Bir zamanlar \"Luna Starliy Starlife\" adında biri vardı. Kız kardeşi Lina ile birlikte The Dragwolfinh adında küçük bir ülkede yaşıyorlardı. Onlar zaman yolcusu ve bilim insanıydılar, yeni planlarını gerçekleştirmede başarılı çocuklardı. Bir gün bir iksir yaptılar ama bu iksir insanları canavara dönüştürüyordu. Luna değiştirilemeyecek bir şey yaptı. Ta ki blackwhite çok uzaklarda yaratılana kadar. Blackwhite, insanların şekline girebilen bir şekil değiştiriciydi. İnsanların zaman çizgisini değiştirebilecek kadar güçlü ve kuvvetliydiler. Dünyayı kontrol etmek istiyorlardı. Bir gün blackwhite zaman çizgisine girdi ve Luna'nın anılarını kontrol altına aldı. Luna her gün çok fazla dejavu yaşıyor, sürekli makaslar görüyor ve onlardan korkuyordu. Luna bir şey fark etti; Luna'nın makas bir eli vardı, onu daha da korkutan devasa bir makas el. Luna bir canavara, yani Blackwhite'a dönüşmeye başladı. Luna, büyük çocuğu olan blackwhite ile konuşmaya çalıştı; eğer onları düzeltebilirse, luna'nın onlara bakacağını söyledi. Blackwhite luna'yı normale döndürdü ve luna'nın kendilerini düzeltmesine izin verdi. Evde luna bunu düzeltmeye çalıştı ama işe yaramadı. Günler, haftalar, aylar geçti ve hala onlara yardım etmeye çalışıyorlardı ama yaptıkları iksir yeterince düzeltilebilir değildi. Luna blackwhite'ı düzeltmek istiyordu ama bu imkansızdı. Blackwhite kaçtı ve er ya da geç karşılaşmayı dilediler. Blackwhite yıllarca dünyanın eski tarihini ziyaret etti. Blackwhite dünyayı ve dünya tarihini yönetmek istiyordu. Luna ise diğer tarafta insanları, en çok da blackwhite'ı düzeltebilecek bir zaman makinesi üzerinde çalışıyordu. Luna, blackwhite'ın düzeltilebilmesi için her gün bu zaman makinesi için çalıştı. Blackwhite'ı düzeltmeyi hayal ettiler, dünyayı değiştirebilecek bir şeyi düzeltmek hakkında kitaplar okudular. Eğer Blackwhite'ı düzeltemezse, Blackwhite dünyayı yok edecekti. Luna sonunda durdu çünkü onları düzeltemiyordu, bu yüzden onları güvenli bir kavanoza hapsetti ve onları kavanoza koymak için bir makine yaptı. Ve işe yaradı, Blackwhite buna çok üzüldü. 5 yıl sonra...",
            "<strong>Luna:</strong> Artık 17 yaşındayım... hala yeni planlar üzerinde çalışıyorum ve arkadaşlarımla takılıyorum... ama sonra güvenli kavanozun açıldığını ve blackwhite'ın kaçtığını gördüm, belki de çok uzaklara... ama bir şeylerin olacağını biliyordum. Sonra buradayım, beyaz boşlukta, silver'ın evinde...",
            "Silver luna'nın elini öptü ve onları tatlı bir ev gibi karşıladı. Luna daha çok kızardı ve durumu bozmamaya çalıştı. Luna, silver'ın odasının tamamen luna'nın resimleriyle dolu olduğunu gördü.",
            "<strong>Silver:</strong> Bunu gördüğünde korkma.. Uzun zamandır seninle tanışmak istiyordum sevgilim...",
            "Silver yüzüne yaklaştı, ikisi de birbirine baktı ama gözleri arzulu olmaya başladı. Gözleri kapalı ve dudakları kilitli bir şekilde öpüştüler, ilk hoş geldin öpücüklerini aldılar. Yavaşça birbirlerine baktılar. Luna olanlardan sonra şok olmuştu. Bunu gizlemeye çalıştı. Luna'nın ağzında cıva tadı gibi tuhaf bir tat vardı. Silver elini tuttu.",
            "<strong>Silver:</strong> Benim adım silver mercury...",
            "<strong>Luna:</strong> Benim adım luna starliy starlife... Seninle tanışmak güzel silver... Peki buraya nasıl geldin?",
            "<strong>Silver:</strong> Şey... Bilmiyorum, burada doğdum ama ailemin nerede olduğunu bilmiyorum. Tek olan ben miyim bilmiyorum ama... Evet, hayat bu sanırım?...",
            "Luna onlara yumuşakça baktı ve luna silver'a mavi bir bileklik verdi.",
            "<strong>Silver:</strong> Vay canına... Teşekkürler luna...",
            "Luna ve silver beyaz boşluktan kaçmaya çalışırlar.",
            "<strong>Silver:</strong> Luna, dragwolfinh'e ışınlanabilir miyiz?... luna???",
            "Luna kendini tuhaf hissetmeye başladı, ellerine baktı ama silver onun korktuğunu görünce luna'yı sakinleştirmeye çalıştı.",
            "<strong>Silver:</strong> Hey... Sorun yok lun-lun.. Senin için buradayım...",
            "<strong>Luna:</strong> Tamam... Hazırım...",
            "Luna'nın arkadaşları luna ve silver'ı görür.",
            "<strong>Filler:</strong> Luna! Sonunda buradasın... Ve sen de kimsin?",
            "<strong>Luna:</strong> Şey... Herkes! Bu silver mercury, kendisi benim erkek arkadaşım..",
            "Herkes silver mercury için mutlu ve heyecanlıydı. Gece vakti luna bu gece için yatakları yapmaya başladı. Silver, luna'nın kıyafetlerinden bazılarını giyiyordu.",
            "<strong>Lina:</strong> Herhangi bir yiyecek türünü sever misin silver?",
            "<strong>Silver:</strong> Şey, pop tarts severim, bilirsin şu atıştırmalık şeyleri..",
            "<strong>Lina:</strong> Vay, bu harika.",
            "Silver sonunda dragwolfinh insanlarını daha fazla tanıdığı için mutluydu. Luna ve diğerleri uyuyakaldı. Luna, blackwhite'ın luna'yı altın kanatları olan bir evrene götürdüğünü gördüğü tuhaf rüyalar görmeye başladı.",
            "<strong>Blackwhite:</strong> Hadi anne uyanma vakti... Parlama zamanı luna...",
            "Luna silver tarafından uyandırıldı.",
            "<strong>Silver:</strong> Luna! LUNA! Tanrıya şükür uyandın..",
            "<strong>Luna:</strong> Ah.. Sırtım mı? Sırtımın arkasında bir şey hissediyorum..",
            "luna sırtının arkasında bir şey hissetti ve bunlar altın kanatlardı, luna bu rüya hakkında endişelenmeye başladı. Bir kabus gibiydi.",
            "<strong>Silver:</strong> İyi misin luna?",
            "<strong>Luna:</strong> İyiyim... Endişelenme..",
            "Luna bunu açıklamak istemedi çünkü durumu daha da tuhaflaştıracaktı.",
            "Tom luna'yı arar.",
            "<strong>Tom:</strong> Selam luna, bugün diğerleriyle dışarı çıkmak ister misin?",
            "<strong>Luna:</strong> Evet tabii dostum hehe..",
            "Dışarıda eğlenmeye başladılar, tom kanatlarıyla uçuyordu. Luna diğerlerini mutlu gördüğü için mutluydu. Dee Lee, Tom için mutlu oluyor ve kızarıyordu çünkü uzun zamandır ona aşıktı. Filler, mr.? ve diğerleri konuşuyordu ama sonra elly adında bozuk, kötü bir robot tom'u öldürmeye çalıştı. Ve tom'un göğsünü yaraladı, tom yere düştü. İnsanlar bunun luna'nın eski projelerinden biri olduğunu düşündü, bu yüzden kavga etmeye başladılar.",
            "<strong>Rammy:</strong> LUNA BU SENİN SUÇUNDU. BU SENİN PROJELERİNDEN BİRİYDİ DEĞİL Mİ?",
            "<strong>Luna:</strong> Hayır.. Yemin ederim ben değildim...",
            "Tom haftalarca hastanede kaldı ve luna kanatlarını verdi, böylece tom tekrar uçabildi. Silver kıskanmıştı çünkü luna ve tom çıkıyordu ama eski okullarındaki insanlardan daha fazla cinselleştirilmiş şakalar aldıkları için bunu bıraktılar. Dee lee tom'un iyi olmasını umuyordu.",
            "<strong>Silver:</strong> Luna...",
            "<strong>Luna:</strong> H-hey sorun yok, iyiyim..",
            "<strong>Silver:</strong> Bu senin suçun değildi..",
            "Luna tom için gerçekten çok üzgündü. Polis lilith ve kaylee luna'yı kötü robot yüzünden tutuklamaya geldi. Karakolda luna'yı elektrikli sandalyeye oturttular.",
            "<strong>Police lilith:</strong> Evet doktor luna, bunu arkadaşın tom'u incitmek için neden yaptın?",
            "<strong>Luna:</strong> Bakın elly'nin benim eski projelerimden biri olduğunu biliyorum ama yemin ederim ben değildim!",
            "<strong>Police kaylee:</strong> Yalancı! Bunu daha fazla insanı incitmek için yaptın, değil mi?",
            "<strong>Luna:</strong> Hayır, ama neden birine zarar vereyim ki?",
            "<strong>Police kaylee:</strong> Bilmiyorum, bunu önce kendine sor!",
            "Elektrik düğmesine bastılar. Luna acı içindeydi.",
            "<strong>Luna:</strong> AHHHHHHGGGGG!! RAHHHHHHH!!",
            "Durdurdular.",
            "<strong>Luna:</strong> Uf... Bundan şimdiden yoruldum...",
            "Silver luna'ya bakıyordu. Polis lilith ve kaylee luna'yı yalnız bıraktı, silver bir sıvı ile ortaya çıktı.",
            "<strong>Silver:</strong> Selam luna, yardım ister misin?",
            "<strong>Luna:</strong> Elbette...",
            "Silver luna'yı yakınına çekti ve onu cıva sıvısıyla öptü. luna cıva tadıyla daha da tuhaf hissetti. Luna ve silver birbirlerine baktılar ve birbirlerinin aşkıyla öpüştüler. Luna ve silver uzun zamandır hissettikleri bu aşk duygusuna sahiptiler. Silver luna'nın elektrikli sandalyeden çıkmasına yardım eder. Luna sonunda silver gibi birine sahip olduğu için mutluydu. Luna ve silver luna'nın gizli laboratuvarına giderler.",
            "<strong>Luna:</strong> Elly'yi sadece daha fazla bitki, ağaç ve başka şeyler yapmak için yaratmıştım.. ama belki de...",
            "luna blackwhite'ın bunu luna'yı Yok Etme planını başlatmak için yaptığını fark etti. Luna biraz zaman istedi çünkü durum daha da tuhaflaşmaya başlamıştı.",
            "<strong>Filler:</strong> Bilirsin pencereyi değil kapıyı kullanabilirdik ama neyse.. luna ne oldu?",
            "Luna onlara ne olduğunu anlatır. Luna elly'yi arıyordu ama rammy ve lily onu dövüş robotu olarak kullanıyordu. İnsanlarla çok fazla dövüşmek istiyorlardı. Rammy dövüşte gerçekten iyidir. Luna robotla dövüşmelerine izin verdi, evde luna ev kıyafetlerini giyiyordu ve silver kapıyı açıp luna'nın kollarını ve bacaklarını gördü.",
            "<strong>Luna:</strong> Lütfen bana bakma..",
            "<strong>Silver:</strong> Hayır, hala çok güzel görünüyorsun sevgilim...",
            "Silver dokunmaya çalıştı ve bunlar biraz derin kesiklerdi, silver kolunu tuttu ve yumuşakça öptü, luna mutluydu.",
            "<strong>Silver:</strong> Luna, kendini iyi hissetmeni sağlayacak bir şey yapmak ister misin?",
            "<strong>Luna:</strong> Evet, tamam!... ",
            "Öpüşmeye başladılar. Luna, silver'ın kucağına oturdu ve öpüşmeye başladılar. Lina sesleri duydu, kapıyı açtı ve onların öpüştüğünü gördü. Lina onları gördükten sonra kapıyı kapattı. Luna ve silver birbirlerine bakıyorlardı. Silver yavaşça onun uyluğunu tuttu, Luna kızararak silver'a baktı. Dudaklarını yavaşça birbirine değdirdiler. Luna ve silver, dragwolfinh'de çok fazla insan kalmadıktan sonra aşıklar gibiydiler. Zaman geçtikçe aşk daha da büyüyordu. Yatağa uzandılar ve birlikte uyudular. Uyurken birbirlerine sarıldılar.",
            "<strong>Lina:</strong> Şey, onlar eğlenceli vakit geçiriyorlardı amaaa... biz yemek yaparken daha çok eğleniyoruz millie.",
            "<strong>Millie:</strong> Kesinlikle evet! Hehehe...",
            "Bikte yemek yapıyorlardı. Yeni yemek türleri öğrenmeye çalışıyorlardı, bu yüzden yeni yemekler yapmaya başladılar. Yemeği birlikte yediler ve gerçekten çok güzeldi. Bu sırada Silver uyandı ve Luna'nın tasmasını ve altın kalp kolyesini gördü. Ayağa kalktı ve kalbin içini açtı, içinde luna'nın altın güçlere sahip olmasını sağlayabilecek bir güç sistemi vardı. Silver duvardaki resimlere yavaşça baktı, bunlar aile ve arkadaş resimleriydi, silver luna ve ailesinin bir resmini gördü. Silver yavaş yavaş ağlamaya başladı, hiç ailesi olmamıştı ve kendisi gibi başka hiçbir mercury insanı olmadığını biliyordu. Luna uyandı ve silver'ın ağladığını gördü. Ayağa kalktılar ve bir şey söylemeden önce silver'a sarıldılar.",
            "<strong>Luna:</strong> Endişelenme, silver'la tanıştırabileceğim bir mürekkep arkadaşım var...",
            "Ertesi gün Filler ve Mr.?'a giderler, onların insanlara karşı her zaman tatlı davranacaklarını biliyorlardı. Mr.?, Silver ile tanıştı ve aile üyesi olup olmadıklerini görmek için bir DNA testi yaptılar, sonuçlara baktılar ve kuzen çıktılar ama birbirlerini daha önce hiç görmemişlerdi. Silver ailesinde bir üye gördüğü için mutluydu. Luna silver adına mutluydu. Ondan sonra Luna'nın köpeği bluey'nin mezarına giderler, mezara bakarlar ve silver luna'nın sessizce ağlamaya başladığını fark eder. Luna çimlerin üzerine oturur ve silver üzüntüyle luna'ya bakar. Hayatta sevdiğin birini kaybetmenin en kötü şey olduğunu bilir. Luna yavaşça çimlerin üzerine uzanır, silver da çimlerin üzerine oturur, silver onlara köpeğini hatırlatacak şeyin ne olabileceğini sorar.",
            "<strong>Luna:</strong> O tasma köpeğimin tasmasıydı.. Onu özlediğim için takıyorum...",
            "Silver tasmaya baktıktan sonra durumu fark etti, geldi ve luna'ya sarıldı. Luna silver'a sarıldıktan sonra ayağa kalktı, küreği kaptı ve mezarı kazmaya başladı. Silver şok olmuştu.",
            "<strong>Silver:</strong> Ne yapıyorsun?...",
            "<strong>Luna:</strong> Ne mi yapıyorum!? Kazıyorum. Onu hayata yeniden döndürebilirim!...",
            "Luna'nın gizli laboratuvarına giderler ve bluey'yi onu tekrar canlandırabilecek bir makineyle yeniden doğurmaya çalışırlar. Luna pek çok kez dener ama başarısız olur ama bir kez daha denerler ve işe yarar. Luna, bluey'ye zombiye dönüşmesini engelleyecek bir iksir içirdi. Luna ayrıca bluey'nin bizim gibi konuşmasını sağlayacak bir tasma da yaptı. Bluey yeniden doğmuştu ve luna köpeğini tekrar gördüğü için mutluydu. Bluey'yi eve götürürler. Lina bluey'yi tekrar gördüğü için mutluydu, luna bluey'nin köpek eşyalarını tekrar eve getirmeye çalışıyordu. Silver fazla köpek maması olmadığını fark eder ve etrafa bakıp içinde çürümüş mama olan bir köpek kasesi görür.",
            "<strong>Silver:</strong> Hey lina? Burada neden çürümüş mama var?",
            "<strong>Lina:</strong> Şey... Bluey araba kazasında öldüğünde luna çürümüş mama yiyordu.",
            "Luna boş gözlerle onlara bakıyordu, henüz kelimeler dökülmemişti.",
            "<strong>Luna:</strong> Silver... Çürümüş mamayı çöpe atabilir misin?..",
            "Luna bluey'ye bakar.",
            "<strong>Luna:</strong> Bluey olmadan hiç kimse için bir hiç olurdum...",
            "Bluey Luna'ya sıkıca sarılır.",
            "<strong>Bluey:</strong> Her şey çok güzel olacak luna..."
        ],
        story2: [
            "Luna yavaşça uyanır. Arkasına bakar, Silver ona sarılmaktadır. İç çamaşırlarıyla duruyorlardır, Luna kalkar ve giyinir. Silver birlikte uyuduklarını bilerek uyanır. Silver sırıtır ve Luna'ya bakar.",
            "<strong>Luna:</strong> Bunu aklından bile geçirme Silver.",
            "<strong>Silver:</strong> Burada olmayı neden sevmiyorsun?",
            "<strong>Luna:</strong> Dragwolfinh tanrılarına gidiyorum, beni konuşmak için davet ettiler.",
            "<strong>Silver:</strong> Demek şimdi gidiyorsun... Daha fazla vaktimiz olabilir sanmıştım.",
            "<strong>Luna:</strong> Kes. Kes. KES. SADECE SİKTİR GİT VE KES ARTIK!!!!",
            "Luna kapıyı kapatır, Silver'ın kafası karışır ama durmaz. Luna en kısa sürede Dragwolfinh tanrılarının yanına gider.",
            "<strong>Luna:</strong> Merhaba? Kimse yok mu? Herhangi biri???",
            "<strong>Miss Gold:</strong> Hoş geldin Dr. Luna Starliy Starlife… Seni davet ettik çünkü müzik melodisi dünyasına yardım etmene ihtiyacımız var.",
            "<strong>Mr. Star:</strong> Sana anahtar olan hayatın müziğini veriyoruz.",
            "<strong>Mr. Devil:</strong> Bunu sana veriyoruz çünkü seni inciten insanlara karşı daha güçlü olman gerekiyor. İnsanların huzurunu sağlayacak olan sensin, bu yüzden şimdi başla.",
            "<strong>Luna:</strong> Yani bu dünyaya barış mı getirecek???",
            "<strong>Miss Gold:</strong> Evet tatlım, bu hayatının yolunu seçebileceğin anlamına geliyor. Adım adım, her hamle seni eğlenceli yaşamaya teşvik edecek…",
            "<strong>Luna:</strong> Ama ya bunları tekrar tekrar yapmayı başaramazsam, yine de arkadaşlarımla birlikte olabilecek miyim?",
            "<strong>Miss Gold:</strong> Evet, yaptığın her hamle hayatında bir seçimdir, doğru hissettirmese bile..",
            "<strong>Mr. Star:</strong> Ama unutma, zaman çizgisini sıfırlamak veya silmek istersen ben her zaman buradayım. Yine de ne kadar uğraşırsan uğraş, üzgün ve hüzünlü olsan bile denemeye devam et.. Ben senin çocukluk hayali arkadaşınım tamam mı? Gece vakti gökyüzüne bakıp yıldızları görmene ihtiyacım var ve o büyük yıldızlardan biri benim…",
            "<strong>Luna:</strong> Tamam o zaman… Şimdi başlayalım..",
            "Dragwolfinh tanrıları Luna'ya bir ruh elementi verir, bu element ritmi zihinlerinde ve kalplerinde tutmalarını sağlar. Luna kalbinin ritmini çalmaya başlar… Erkek kardeşi Mike gibi bir elektro gitar alır, Luna zihninde bir melodi çalmaktan rahatlamış ve mutlu hissetmektedir… Luna ruh elementini görerek yavaşça gözlerini açar.",
            "<strong>Luna:</strong> Vay canına… Hiç bu kadar iyi hissetmemiştim..",
            "<em>geçmişe dönüşler (flashbacks)</em>",
            "Yıllar önce.. Ben (Luna) ve Mike yakın kardeşlerdik… Mike ona tecavüz edip istismar etmeden önce…",
            "<strong>Mike:</strong> Luna. Luna…….LUNAAAAAA!!!!!",
            "Luna bir anlığına kendine gelir.. Kapıyı kilitlemeye çalışmaktadır. Mike açmaya çalışır…",
            "<strong>Luna:</strong> HAYIR BANA ZARAR VERİYORSUN!!! HAYIR MIKE SENİ İSTEMİYORUM…",
            "Luna duş alır ve bacaklarından kan damlamaktadır. Luna banyoda ağlamaya başlar, kanama durana kadar bekler… Mike'ın ruhu Luna'nın bedenine bakar, Mike Luna'ya bakar.",
            "<strong>Mike:</strong> Beni unutmaya mı çalışıyorsun Luns?",
            "<strong>Luna:</strong> Beni yara izlerimin yüzeyinin altına çektin. Şimdi beni burada yalnız bırak.",
            "<strong>Mike:</strong> Kazanamayacağını biliyorsun çünkü sen bir eziksin, hiç kazanma şansın olmadı. Kemiklerimin altına bak bakalım senin için yeterince umursuyor muyum.",
            "(Her şey hoş bir mutluluk kokusuyla başlar ama geçmişe bakmak kendilerini yakmalarına neden olur ve bunun için iyi olmaya alışmışlardır ama zaman geçtikçe birbirlerinden nefret edenler gibi davranmaya başlarlar. Basit hatalar günlük sağlıklarını daha da kötüleştirir…)",
            "<strong>Mike:</strong> Şimdi sessiz mi olacaksın yoksa beni affedecek misin?",
            "<strong>Luna:</strong> Hayır seni asla affetmeyeceğim Mike.",
            "<strong>Mike:</strong> Ne dedin sen!?!",
            "<strong>Luna:</strong> Seni affetmiyorum dedim…",
            "Mike ellerini Luna'nın boynuna koyar ve onu ateş elementi gibi yakar.",
            "<strong>Luna:</strong> AHHHHHHHHH!!!…",
            "<strong>Mike:</strong> LUNA SANA ÇOK ŞANS VERDİM!!! DOĞRU ANLAMIYOR MUSUN?!!??! Sana ihtiyacım vardı.",
            "<strong>Luna:</strong> MIKE BIRAK BENİ!! İlk önce senin gitmeni istemiştim.",
            "Mike ona tokat atar ve ona bakar.",
            "<strong>Luna:</strong> Dur dedim.",
            "Odayı hiçbir pişmanlık olmadan sadece acının sessizliği doldurur. Luna yavaşça yok olmaya başlar… Mike ise içki almak için odadan çıkar. Luna haplarını yutar ve son nefeslerini almaya çalışır. Luna giyinir ve gece dışarıda yürür.",
            "<strong>Lina:</strong> Luna? Burada ne yapıyorsun?",
            "Lina onun vücudundaki izleri görür…",
            "<strong>Lina:</strong> Aman Tanrım, bunu sana kim yaptı kardeş kim??",
            "<strong>Luna:</strong> Şey.. Mike..",
            "<strong>Lina:</strong> Bekle, Mike mı!?! Nasıl??!",
            "Luna durumu Lina'ya açıklar, Lina Mike'tan intikam almak ister.",
            "<strong>Luna:</strong> Bak sadece biraz temiz hava almam gerekiyor tamam mı?",
            "<strong>Lina:</strong> Ama kendine bak, hırpalanmış gibi görünüyorsun…",
            "<strong>Luna:</strong> İyi olacağım, sadece eve git tamam mı?",
            "Luna bunu unutmak için biraz şarap içer. Berri Luna'yı görür.",
            "<strong>Berri:</strong> Luna burada dışarıda ne yapıyorsun!?",
            "<strong>Luna:</strong> Uh-uh-selam Berri~…",
            "<strong>Berri:</strong> *İç çeker*.. Tamam Luna, seni evime götürüyorum.",
            "Berri'nin evinde…",
            "<strong>Luna:</strong> Ah-uh-umm.. Berri? Ne yapıyorsun?",
            "<strong>Berri:</strong> İzlerin geçmesine yardım etmeye çalışıyorum, nasıl hissediyorsun Luns?",
            "<strong>Luna:</strong> Oh şimdi harika hissediyorum, şu an çok uykum var.",
            "<strong>Berri:</strong> Birlikte uyumamızı ister misin?",
            "Luna ve Berri kızarır, Luna evet der ve birlikte uyurlar.",
            "<strong>Berri:</strong> Hey Luna?",
            "<strong>Luna:</strong> Efendim??",
            "<strong>Berri:</strong> Seni seviyorum.",
            "<strong>Luna:</strong> Ben de seni seviyorum Berri…",
            "Öpüşürler ve uyuyakalırlar. Sabahleyin Berri kalkar ve Luna ile kendisi için kahvaltı hazırlar.",
            "Luna bir kabus görür, başka bir yere benzeyen mavi bir dünyada mavi renktedir. Boynuzları, kuyruğu ve şeytan kanatları olan kırmızı bir adam görür.",
            "<strong>Luna:</strong> Merhaba efendim, şu an neredeyim?",
            "<strong>Kırmızı Adam:</strong> Burası hüzün dünyası ve benim adım da Mike.",
            "<strong>Luna:</strong> Mike..? Tamam Mike ama buradan nasıl kaçabilirim??",
            "<strong>Mike:</strong> Bilmiyorum ama sana ihtiyacın olan bir şey verebilirim…",
            "Mike küçük bir nesne verir.",
            "<strong>Luna:</strong> Oh um bu parmaklarımı biraz acıtıyor ama teşekkürler sanırım…",
            "<strong>Mike:</strong> Bekle sen Luna Starliy Starlife'sın değil mi?",
            "Luna ilk başta şok olmuş görünür, Mike ona gözlerinde şehvetle bakar.",
            "<strong>Mike:</strong> Sanırım bu evet demek, o zaman iyi şanslar Luna.",
            "Luna hala bu kişinin ona neden küçük bir nesne verdiğini merak etmektedir. Luna ona bakar, keskin bir şeydir… Yavaşça dünyaya sel gibi yağmur yağmaya başlar ve Luna onunla birlikte boğulur. Luna uyanır, yara izi var mı diye kontrol eder, kalkar aynaya bakar. Luna'nın elleri sıcaktır, Berri onu fark eder ve kontrol eder.",
            "<strong>Berri:</strong> Luna iyi misin?",
            "Luna'nın nefesi kesilmiştir.",
            "<strong>Berri:</strong> Tamam şimdi yavaşça nefes al ve nefes ver. Bu seni daha iyi hissettirecektir.",
            "Luna nefes almaya başlar.",
            "<strong>Berri:</strong> Peki ne oldu?",
            "<strong>Luna:</strong> Bir kabus gördüm, adı Mike olan kırmızı bir adam kim olduğumu biliyordu…",
            "<strong>Berri:</strong> Luna bir sarılmaya ya da başka bir şeye ihtiyacın var mı?",
            "<strong>Luna:</strong> Belki bir içki beni iyi edebilir.",
            "Luna bir bira içer, Berri'ye bakar.",
            "<strong>Luna:</strong> Sence Mike gelecekte bana gelecek mi?",
            "<strong>Berri:</strong> Bilmiyorum ama seni koruyacağım.",
            "<em>geçmişe dönüş bitti</em>",
            "Berri Luna'nın evine bakar, Berri'nin gözünde artık tek gözlük bir yara izi vardır. Berri Silver'ı görür.",
            "<strong>Berri:</strong> Bu adamın neden Luna ile olduğunu merak ediyorum.",
            "<strong>Xen:</strong> Yani o adamı ölene kadar kovalayacak mısın?",
            "<strong>Berri:</strong> Hayır hayır sadece merak ediyorum…",
            "<strong>Xen:</strong> Anlıyorum, Luna'yı özledin değil mi?",
            "<strong>Berri:</strong> Evet ama onu tekrar daha kötü hale getirmek istemiyorum.",
            "Xen ve Berri Luna'nın evine gidip kapıyı çalarlar, Silver açar.",
            "<strong>Silver:</strong> Oh selam, Luna'yı mı arıyordunuz? Şey, o burada değil o yüzden-",
            "<strong>Berri:</strong> Hayır. Seninle konuşacağız, Silver Mercury.",
            "Silver onları içeri davet eder.",
            "<strong>Berri:</strong> Yani sen Luna'nın yeni erkek arkadaşısın değil mi?",
            "<strong>Silver:</strong> Evet yani, ne sandın ki?",
            "Berri öfkelenir, Silver'a bakar.",
            "<strong>Berri:</strong> Buradaki amacın ne?",
            "<strong>Silver:</strong> Şey, onun daha iyi olmasına yardım edeceğim.",
            "<strong>Berri:</strong> Yalancı…",
            "Silver'ın kafası karışmıştır.",
            "Berri Silver'ı yumruklamaya başlar, Xen bakar ama ona yardım etmez.",
            "<strong>Berri:</strong> BEN ONUN İLK ERKEK ARKADAŞIYDIM, EĞER HİÇBİR ŞEY OLMAMIŞ GİBİ DAVRANACAKSAN SENİ GEBERTENE KADAR DÖVERİM.",
            "<strong>Silver:</strong> Heh.. Demek sen onun 'kötü çocuğu'sun ha? Bil bakalım ne var, ona tecavüz edecektim ve-",
            "Berri bıçağı alır ve onu bıçaklar, Silver bir cıva olduğu için siyan (camgöbeği) rengi kanı vardır.",
            "<strong>Silver:</strong> Ah! Onun için hastasın Berri. Benim ne kadar güçlü olduğumu asla anlayamayacaksın.",
            "<strong>Berri:</strong> O İKİZ ERKEK KARDEŞİ TARAFINDAN TECAVÜZE UĞRADI, İSTİSMAR EDİLDİ VE BİR BEBEK DÜNYAYA GETİRDİ!!",
            "Silver şoke olmuştur.",
            "<strong>Silver:</strong> Bekle-",
            "<strong>Berri:</strong> HAYIR BAHSE GİRERİM SEN DE MIKE GİBİ OLACAKSIN DEĞİL Mİ!?!",
            "Maoki onlara bakar…",
            "<strong>Maoki:</strong> Baba…?",
            "<strong>Berri:</strong> Maoki..",
            "<strong>Maoki:</strong> Baba ne yapıyorsun?",
            "<strong>Berri:</strong> Hayır odana git, ciddi konuşuyoruz…",
            "<strong>Maoki:</strong> Ama baba-",
            "<strong>Berri:</strong> ODANA GİT DEDİM!!",
            "Maoki odasına gider…",
            "<strong>Silver:</strong> Yani Maoki Luna'nın çocuğu mu..?",
            "<strong>Berri:</strong> Evet, bu adamın onu bu güne kadar avlayacağını hiç düşünmemiştim.",
            "<strong>Silver:</strong> Bak dostum, bunun ciddi olduğunu biliyorum ama onu mutlu edebiliriz.",
            "<strong>Berri:</strong> Senin gibi adamlar midemi bulandırıyor, Silver!",
            "<strong>Silver:</strong> En azından onun iyi hissetmesini sağlamak için kendimi geliştirmeme yardım edebilirsin.",
            "<strong>Berri:</strong> Güzel ama eğer onun duygularını incitirsen seni parça pinçik ederim…",
            "Berri ve Xen evden ayrılır, Luna Berri'nin yanına gider.",
            "<strong>Luna:</strong> Berri bak sonunda güçlerim var ve-",
            "<strong>Berri:</strong> Dinle, konuşmamız gerekiyor Luna.",
            "Luna bir anlığına şoke olur ve korkar.",
            "<strong>Berri:</strong> Luna, Silver sana tecavüz edecekti.",
            "Luna sessiz kalır ve yavaşça titrer.",
            "<strong>Luna:</strong> N-ne?.. Berri ben-",
            "<strong>Berri:</strong> Yeni erkek arkadaşının sana tecavüz edeceğini söylediyim.",
            "<strong>Luna:</strong> O.. Bunu yapacak mıydı?",
            "<strong>Berri:</strong> Evet, bugün Xen ile öğrendim.",
            "Luna ağlamaya başlar, Berri Luna'ya yumuşakça bakar ve çenesini tutar.",
            "<strong>Berri:</strong> Bebeğim, zor olduğunu biliyorum ama ben-",
            "<strong>Luna:</strong> BUNU NASIL YAPAR!? O BENİM HER ŞEYİMDİ!!",
            "<strong>Berri:</strong> İLK ÇIKTIĞIMIZDA SEN DE BENİM HER ŞEYİMDİN LUNA!!",
            "Luna Berri'ye bakar, Berri'nin gözyaşları süzülmeye başlar.",
            "<strong>Luna:</strong> Beni öpmeni ister misin?",
            "<strong>Berri:</strong> Yani bu senin seçimin, öpülecek bir adam değilim gerçi.",
            "Luna yavaşça Berri'nin çizilmiş gözünü ve ardından ağzını öper…",
            "<strong>Luna:</strong> Mh~ Berri, tadın hala her zamanki gibi aynı.",
            "<strong>Berri:</strong> Seni özledim, Luns.",
            "<strong>Luna:</strong> Şimdi sana bir şarkı söylemem gerekiyor.",
            "Luna Berri için bir şarkı söyler, daha sonra Luna eve gider ve Silver ile konuşur.",
            "<strong>Silver:</strong> Luna eve hoş geldin.",
            "<strong>Luna:</strong> …",
            "<strong>Silver:</strong> Tatlım neden bu kadar sessizsin?",
            "<strong>Luna:</strong> Silver beni yalnız bırak.",
            "<strong>Silver:</strong> Ne-",
            "<strong>Luna:</strong> BENİ YALNIZ BIRAK!!!",
            "<strong>Silver:</strong> Luna seni anlamıyorum.",
            "<strong>Luna:</strong> RAGHH! SADECE SİKTİR GİT!!!",
            "Luna Maoki'nin yanına gider, Maoki'ye bakar.",
            "<strong>Luna:</strong> Bebeğim, Maoki",
            "<strong>Maoki:</strong> Anneciğim, korkuyorum…",
            "<strong>Luna:</strong> Buradayım çocuğum.",
            "Luna ve Maoki birbirine sarılır. Maoki, Luna'nın kollarında ağlar.",
            "<strong>Luna:</strong> Bebeğim, ağlama",
            "<strong>Maoki:</strong> Ben bir hata mıyım anneciğim?",
            "<strong>Luna:</strong> Hayır bebeğim, değilsin. Bunu sana kim söyledi?",
            "<strong>Maoki:</strong> Rüyalarımda Mike adında birini gördüm ve bana bunu söyledi.",
            "Luna şoke olur, Maoki'ye bir peluş oyuncak verir.",
            "<strong>Maoki:</strong> Anneciğim?",
            "Luna kalp krizi geçirir ve yere yığılır.",
            "<strong>Maoki:</strong> ANNEEEE!!!",
            "Ambulans eve gelir ve Luna'yi götürür…"
        ]
    }
};

let currentLang = 'en';

document.addEventListener("DOMContentLoaded", () => {
    selectLanguage('en');
});

function toggleLangMenu() {
    document.getElementById("lang-dropdown").classList.toggle("show");
}

window.onclick = function(event) {
    if (!event.target.matches('.lang-trigger-btn') && !event.target.parentElement.matches('.lang-trigger-btn')) {
        const dropdown = document.getElementById("lang-dropdown");
        if (dropdown.classList.contains('show')) {
            dropdown.classList.remove('show');
        }
    }
}

function selectLanguage(lang) {
    currentLang = lang;
    
    document.getElementById("txt-powered").innerText = translations[lang].powered;
    document.getElementById("btn-ch1").innerText = translations[lang].ch1_nav;
    document.getElementById("btn-ch2").innerText = translations[lang].ch2_nav;
    document.getElementById("ch1-title").innerText = translations[lang].ch1_title;
    document.getElementById("ch2-title").innerText = translations[lang].ch2_title;
    document.getElementById("txt-published-by").innerText = translations[lang].published_by;
    
    // Bölüm 1 İçeriği Güncelleme
    const container1 = document.getElementById("ch1-text-container");
    container1.innerHTML = "";
    translations[lang].story1.forEach(paragraph => {
        const pElement = document.createElement("p");
        pElement.innerHTML = paragraph;
        container1.appendChild(pElement);
    });

    // Bölüm 2 İçeriği Güncelleme
    const container2 = document.getElementById("ch2-text-container");
    container2.innerHTML = "";
    translations[lang].story2.forEach(paragraph => {
        const pElement = document.createElement("p");
        pElement.innerHTML = paragraph;
        container2.appendChild(pElement);
    });
    
    document.getElementById("lang-dropdown").classList.remove("show");
}

function changeChapter(chapterNumber) {
    const chapters = document.querySelectorAll('.chapter-content');
    chapters.forEach(chapter => {
        chapter.classList.remove('active-content');
    });

    const buttons = document.querySelectorAll('.nav-btn');
    buttons.forEach(button => {
        button.classList.remove('active');
    });

    const activeChapter = document.getElementById(`chapter-${chapterNumber}`);
    const activeButton = document.getElementById(`btn-ch${chapterNumber}`);

    if (activeChapter && activeButton) {
        activeChapter.classList.add('active-content');
        activeButton.classList.add('active');
        
        window.scrollTo({
            top: activeChapter.offsetTop - 150,
            behavior: 'smooth'
        });
    }
}
